#!/usr/bin/env bash
set -e

SERVICE_NAME="tgbot"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
CURRENT_USER=$(whoami)
CURRENT_DIR=$(pwd)
PYTHON_BIN="${CURRENT_DIR}/tgbot/bin/python3"
MAIN_PY="${CURRENT_DIR}/main.py"

echo "This script is generated by Gemini on Google AI Studio."

if [ ! -f "$PYTHON_BIN" ]; then
    echo "[!] Error: Can't find Python virtual environment at: $PYTHON_BIN. Please try again after creating a venv according to the README.md."
    exit 1
fi

echo "Creating ${SERVICE_FILE}..."

sudo bash -c "cat <<EOF > ${SERVICE_FILE}
[Unit]
Description=Telegram Bot Service
After=network.target

[Service]
Type=simple
User=${CURRENT_USER}
WorkingDirectory=${CURRENT_DIR}
ExecStart=${PYTHON_BIN} ${MAIN_PY}
Restart=always
RestartSec=5
EnvironmentFile=-${CURRENT_DIR}/.env
# Add '-' means even if .env file isn't exit, it won't cause error

[Install]
WantedBy=multi-user.target
EOF"

echo "Reloading systemd..."
sudo systemctl daemon-reload

echo "Enabling auto run on start and starting service..."
sudo systemctl enable --now ${SERVICE_NAME}.service

echo "=== Setup finished. Service status: ==="
sudo systemctl status ${SERVICE_NAME}.service --no-pager